name: Update Iran SmartDNS List

on:
  schedule:
    - cron: '0 3 * * 0'   # Weekly Sunday 03:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download domains list
        run: |
          curl -L -o domains.txt \
          https://github.com/bootmortis/iran-hosted-domains/releases/latest/download/domains.txt

      - name: Generate iran.conf
        run: |
          echo "nameserver /ir/iran" > iran.conf

          grep -v '\.ir$' domains.txt \
            | sort -u \
            | sed 's/^/nameserver \\/./' \
            | sed 's/$/\\/iran/' \
            >> iran.conf

      - name: Commit if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add iran.conf

          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "Weekly update"
            git push
          fi
